INSERT INTO permissao(nome) VALUES('CADASTRAR_GRUPO');
INSERT INTO permissao(nome) VALUES('CADASTRAR_MESA');
INSERT INTO permissao(nome) VALUES('CADASTRAR_PIZZA');
INSERT INTO permissao(nome) VALUES('CADASTRAR_PRODUTO');
INSERT INTO permissao(nome) VALUES('CADASTRAR_PROMOCAO');
INSERT INTO permissao(nome) VALUES('FINANCEIRO');